CWB.App/Models/Routings/LocationVM.cs
namespace CWB.App.Models.Routings
{
    public class LocationVM
    {
       public int Id { get; set; }
       public string Name { get; set; }
    }
}

CWB.App/Models/Routings/RoutingListItemVM.cs
using System.Collections;
using System.Collections.Generic;

namespace CWB.App.Models.Routing
{
    public class RoutingListItemVM
    {
        public long ManufacturedPartId { get; set; }
        public string PartNo { get; set; }
        public string CompanyName { get; set; }
        public int CompanyId { get; set; }
        public string PartDescription { get; set; }
        public string Status { get; set; }
        public int RoutingId { get; set; } //with/without
        public string MasterPartType { get; set; }
        public bool HasRouting { get; set; }
        public int NoOfRoutes { get; set; } = 0;

        public IEnumerable<RoutingVM> RoutingVMs { get; set; }
    }
}

CWB.App/Models/Routings/RoutingStepMachineVM.cs
using CWB.App.AppUtils;
using System;
using System.ComponentModel;
using System.Text.Json.Serialization;

namespace CWB.App.Models.Routing
{
    public class RoutingStepMachineVM
    {
        public long RoutingStepMachineId { get; set; }
        public long TenantId { get; set; }
        public long MachineId { get; set; }
        public long RoutingStepId { get; set; }
        public long OrigStepMachineId { get; set; } = 0;

        //[JsonConverter(typeof(TimeSpanToStringConverter))]
        public string SetupTime { get; set; }
        //[JsonConverter(typeof(TimeSpanToStringConverter))]
        public string FloorToFloorTime { get; set; }
        //[JsonConverter(typeof(TimeSpanToStringConverter))]
        public string FirstPieceProcessingTime { get; set; }
        public int NoOfPartsPerLoading { get; set; }

        public int PreferredMachine { get; set; }
        public string StrPreferredMachine { get; set; } = string.Empty;
        public string BGColor { get; set; }
        public string Name { get; set; } = "NA";
    }
}

CWB.App/Models/Routings/RoutingStepPartVM.cs
namespace CWB.App.Models.Routing
{
    public class RoutingStepPartVM
    {
        public long BOMId { get; set; }

        public long ManufacturedPartId { get; set; }
        public string PartDescription { get; set; }
        public long StepPartId { get; set; }
        public long RoutingStepId { get; set; }
        public long OrigStepPartId { get; set; } = 0;
        public long PartId { get; set; }
        public decimal QuantityAssembly { get; set; }
        public string PartNo {  get; set; }

        public int TenantId { get; set; }


    }
}

CWB.App/Models/Routings/RoutingStepSupplierVM.cs
using System;

namespace CWB.App.Models.Routing
{
    public class RoutingStepSupplierVM
    {
        public long RoutingStepSupplierId { get; set; }
        public long TenantId { get; set; }
        public long SupplierId { get; set; }
        public long RoutingStepId { get; set; }
        public int OutSourceDays { get; set; }
        public int ShareOfBusiness { get; set; }
        public string Notes { get; set; }
        public string Name { get; set; } = "NA";
    }
}

CWB.App/Models/Routings/RoutingStepVM.cs
namespace CWB.App.Models.Routing
{
    public class RoutingStepVM
    {
        public long StepId { get; set; }
        public long OrigStepId { get; set; } = 0;
        public long RoutingId { get; set; } //FK
        public string StepNumber { get; set; }//UNIQUE with RoutingId
        public string StepDescription { get; set; }
        public string StepOperation { get; set; } //Operation List
        public string StepLocation { get; set; }
        public int StepSequence { get; set; }

        public string Status { get; set; } = "Active";

        public int NumberOfSimMachines { get; set; }

        public int TenantId {  get; set; }
    }
}

CWB.App/Models/Routings/RoutingVM.cs
namespace CWB.App.Models.Routing
{
    public class RoutingVM
    {
        public int RoutingId { get; set; }
        public string RoutingName { get; set; }
        public long ManufacturedPartId { get; set; }
        public int OrigRoutingId { get; set; } = 0;
        public int PreferredRouting { get; set; } = 0;
        public int Deleted { get; set; } = 0;
        public long MKPartId { get; set; }
        public int TenantId { get; set; }
        public string Status { get; set; }
        public string CreationDate { get; set; }

        //pass values to go to the next page
        public string NRCompanyName {  get; set; }
        public string NRPartNo { get; set;}
        public string NRPartDescription { get; set; }
        public string BGColor { get; set; }
        public string StrPreferredRouting { get; set; } = string.Empty;
    }
}

CWB.App/Models/Routings/StepBOMVM.cs
namespace CWB.App.Models.Routing
{
    public class StepBOMVM
    {
        //DbPart--Start
        public int BOMPartId { get; set; }
        public decimal Quantity { get; set; }
        public long BOMManufPartId { get; set; }
        public string? BOMPartDesc { get; set; }
        //DbPart--End
        public long MPBOMId { get; set; }
        public string BOMPartNo { get; set; }
        public decimal QuantityUsed { get; set; }
        public decimal BalanceQuantity { get; set; }

        public int StepPartId { get; set; }
        public int RoutingStepId {  get; set; }

        public long TenantId { get; set; }
    }
}

CWB.App/Models/Routings/SubConDetailsVM.cs
namespace CWB.App.Models.Routing
{
    public class SubConDetailsVM
    {
        public int NoOfOperations { get; set; }
        public int SubConDetailsId{ get; set; }
        public int RoutingStepId { get; set; }
        public int SupplierId { get; set; }
        public string WorkDone { get; set; }
        public string TransportTime { get; set; }
        public string CostPerPart { get; set; }
        public long OrigSubConId { get; set; } = 0;
        public string Notes { get; set; }
        public int Deleted { get; set; } = 0;
        public int PreferredSubcon { get; set; } = 0;

        public int TenantId { get; set; }
        //pass values to go to the next page
        
        public string Company {  get; set; }
        public string BGColor { get; set; }
        public string StrPreferredSubCon { get; set; } = string.Empty;
    }
}

CWB.App/Models/Routings/SubConWorkStepDetailsVM.cs
namespace CWB.App.Models.Routing
{
    public class SubConWorkStepDetailsVM
    {

        public int SubConWSDetailsId { get; set; }
        public int RoutingStepId { get; set; }
        public int SubConDetailsId { get; set; }
        public string WorkStepDesc { get; set; }
        public int MachineType { get; set; }
        public string SetupTime { get; set; }
        public string FloorToFloorTime { get; set; }
        public int NoOfPartsPerLoading { get; set; }
        public long OrigSubConWSId { get; set; } = 0;
        //pass values to go to the next page
        public string NRCompanyName {  get; set; }
        public string NRPartNo { get; set;}
        public string NRPartDescription { get; set; }
        public string BGColor { get; set; }
        public string StrPreferredRouting { get; set; } = string.Empty;
        public int TenantId { get; set; }
    }
}

CWB.App/Controllers/RoutingsController.cs
using CWB.App.Models.Contacts;
using CWB.App.Models.Routing;
using CWB.App.Models.Routings;
using CWB.App.Services.Masters;
using CWB.App.Services.Routings;
using CWB.Constants.UserIdentity;
using CWB.Logging;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Query.Internal;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CWB.App.Controllers
{
    [Authorize(Roles = Roles.ADMIN)]
    public class RoutingsController : Controller
    {
        private readonly ILoggerManager _logger;
        private readonly IRoutingService _routingService;
        private readonly IMastersServices _mastersServices;
        private readonly IMachineService _machineService;

        public RoutingsController(ILoggerManager logger, IMachineService machineService, IRoutingService routingService,IMastersServices mastersServices)
        {
            _logger = logger;
            _routingService = routingService;
            _mastersServices = mastersServices;
            _machineService = machineService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> RoutingListItems()
        {
            var result = await _routingService.GetRoutingListItems();
            return Json(result);
        }
        //GetRoutingListItmes

        [HttpPost]
        public async Task<IActionResult> AddNewRouting(RoutingVM model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var result = await _routingService.Routing(model);
            return Ok(result);
        }

        [HttpPost]
        public async Task<IActionResult> AltRouting(RoutingVM model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var result = await _routingService.AltRouting(model);
            return Ok(result);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteRouting(int routingId)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var result = await _routingService.DeleteRouting(routingId);
            return Ok(result);
        }

        //preferredsubcon
        [HttpGet]
        public async Task<IActionResult> PreferredSubCon(int subConDetailsId)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var result = await _routingService.PreferredSubCon(subConDetailsId);
            return Ok(result);
        }
        [HttpPost]
        public async Task<IActionResult> PreferredRouting(RoutingVM model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var result = await _routingService.PreferredRouting(model);
            return Ok(result);
        }


        public async Task<IActionResult> RoutingDetails(int manufPartId,string partType)
        {
            var result = await _routingService.GetRoutingListItems();
            var query = from litem in result
                        where litem.ManufacturedPartId == manufPartId
                        select litem;
            RoutingListItemVM routingListItemVM = query.FirstOrDefault();
            if(routingListItemVM == null)
            {
                routingListItemVM = new RoutingListItemVM();
                routingListItemVM.MasterPartType = partType;
                routingListItemVM.RoutingVMs = new List<RoutingVM>();
            }
            else
            {
                var resultList = await _routingService.Routings(manufPartId);
                routingListItemVM.MasterPartType = partType;
                routingListItemVM.RoutingVMs = resultList.ToList();
            }
            return View(routingListItemVM);
        }

        [HttpPost]
        public async Task<IActionResult> CreateAltRouting(RoutingVM model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var result = await _routingService.Routing(model);
            return Ok(result);
        }

        public IActionResult AddNextStep()
        {
            return Ok("Ok");
        }

        [HttpPost]
        public async Task<IActionResult> SaveStep(RoutingStepVM model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var result = await _routingService.RoutingStep(model);
            return Ok(result);
        }

       
        public async Task<IActionResult> DelStep(int stepId)
        {
            var result = await _routingService.DeleteStep(stepId);
            return Ok(result);
        }

        [HttpPost]
        public async Task<IActionResult> AddBomToAssembly(RoutingStepPartVM model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var result = await _routingService.RoutingStepPart(model);
            return Ok(result);
        }

        public async Task<IActionResult> RoutingSteps(int routingId)
        {
            var result = await _routingService.RoutingSteps(routingId);
            return Ok(result);
        }

        public async Task<IActionResult> StepParts(int stepId)
        {
            var result = await _routingService.StepParts(stepId);
            return Ok(result);
        }


        public async Task<IActionResult> BOMs(int manufId, int stepId)
        {
            var boms = await _mastersServices.BOMS(""+manufId);
            var manfsps = await _routingService.StepPartsByManufId(manufId);
            var stepparts = await _routingService.StepParts(stepId);

            var query = from bom in boms
                        select new StepBOMVM
                        {
                            BOMPartNo = bom.BOMPartNo,
                            BOMManufPartId = bom.BOMManufPartId,
                            BOMPartId = bom.BOMPartId,
                            BOMPartDesc = bom.BOMPartDesc,
                            MPBOMId = bom.MPBOMId,
                            Quantity = bom.Quantity,
                            QuantityUsed = 0,
                            BalanceQuantity = bom.Quantity,
                            StepPartId = -1,
                            RoutingStepId = -1
                        };
            List<StepBOMVM> lst = query.ToList();
            //Calculate balance quantity for boms
            try
            {
                foreach (RoutingStepPartVM sp in manfsps)
                {
                    foreach (StepBOMVM spbom in lst)
                    {
                        if (spbom != null && sp != null)
                        {
                            if (spbom.MPBOMId == sp.BOMId)
                            {
                                spbom.QuantityUsed += sp.QuantityAssembly;
                                spbom.BalanceQuantity = spbom.Quantity - spbom.QuantityUsed;
                            }
                        }
                    }
                }
            }
            catch (Exception ex) {
                string msg = ex.InnerException.Message;
                string src = ex.InnerException.Source;
            }
            //reset quantity used on BOM... just for display purpoo
            foreach (StepBOMVM spbom in lst)
            {
                spbom.QuantityUsed = 0;
            }
            List<StepBOMVM> list1 = new List<StepBOMVM> ();
            foreach (RoutingStepPartVM sp in stepparts)
            {
                foreach (StepBOMVM bom in lst)
                {
                    if (bom.MPBOMId == sp.BOMId)
                    {
                        StepBOMVM obj = new StepBOMVM {
                            BOMPartNo = bom.BOMPartNo,
                            BOMManufPartId = bom.BOMManufPartId,
                            BOMPartId = bom.BOMPartId,
                            BOMPartDesc = bom.BOMPartDesc,
                            MPBOMId = bom.MPBOMId,
                            Quantity = 0,
                            QuantityUsed = sp.QuantityAssembly,
                            BalanceQuantity = 0,
                            StepPartId = (int)sp.StepPartId,
                            RoutingStepId = (int)sp.RoutingStepId
                        };
                        list1.Add(obj);
                        break;
                    }
                }
            }
            lst.AddRange(list1);
            return Ok(lst);
        }

        public async Task<IActionResult> StepBOMs(int stepId)
        {
            var result = await _routingService.StepParts(stepId);
            return Ok(result);
        }



        public IActionResult   Routings(int manufPartId)
        {
            return Ok("hello");
        }



        [HttpPost]
        public async Task<IActionResult> SaveStepSupplier(RoutingStepSupplierVM model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var result = await _routingService.RoutingStepSupplier(model);
            return Ok(result);
        }
        [HttpPost]
        public async Task<IActionResult> SaveStepMachine(RoutingStepMachineVM model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var result = await _routingService.RoutingStepMachine(model);
            return Ok(result);
        }

        public async Task<IActionResult> PreferredStepMachine(string routingStepId, string routingStepMachineId, int maxMachineCount)

CWB.App/Views/Routings/RoutingDetails.cshtml
@{
    ViewData["Title"] = "Routing";
}
@model CWB.App.Models.Routing.RoutingListItemVM
<input value="M-IR" type="hidden" id="hdn-nav-menu" />
<div class="content">
    <div class="row">
        <div class="col-xl-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-9">
                            <div class="table-responsive">
                                <table class="table table-sm text-center vam">
                                    <tbody>
                                        <tr>
                                            <th>
                                                <h4>Routing</h4>
                                            </th>
                                            <td>
                                                <span class="h6">Company :</span> @Html.DisplayFor(model => model.CompanyName)
                                            </td>
                                            <td>
                                                <span class="h6">Part No:</span>  @Html.DisplayFor(model => model.PartNo)
                                            </td>
                                            <td>
                                                <span class="h6">Part Description:</span> @Html.DisplayFor(model => model.PartDescription)
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="table-responsive   display-none ">
                                <table class="table table-sm text-end">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <button class="btn btn-sm btn-dark" title="Close & Return to Previous Screen / Menu Item" data-plugin="tippy" data-tippy-placement="top"><span class="fon-we-700">Target Date :</span> 12/08/2022</button>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="col-md-1">
                            <div class="table-responsive">
                                <table class="w-100 text-end ">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <a asp-action="Index" asp-controller="Routings">
                                                    <button type="button" class="btn-close"></button>
                                                </a>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!-- ================================ -->
                        <!-- ================================ -->
                        <div class="col-md-12 mt-n2">
                            <ul class="nav nav-tabs nav-pills nav-justified navtab-bg font-12">
                                <li class="nav-item" id="RoutingAvailable">
                                    <a href="#rs2" data-bs-toggle="tab" aria-expanded="true" class="nav-link active">
                                        <span class="d-inline-block d-sm-none">Routing Available</span>
                                        <span class="d-none d-sm-inline-block">Routing Available</span>
                                    </a>
                                </li>
                                <li class="nav-item" id="RoutingDetails">
                                    <a href="#rou-det" data-bs-toggle="tab" aria-expanded="true" class="nav-link">
                                        <span class="d-inline-block d-sm-none">Routing Details</span>
                                        <span class="d-none d-sm-inline-block">Routing Details</span>
                                    </a>
                                </li>
                                <li class="nav-item" id="RoutingStepDetails">
                                    <a href="#rsd" data-bs-toggle="tab" aria-expanded="false" class="nav-link">
                                        <span class="d-inline-block d-sm-none">Routing Step Details</span>
                                        <span class="d-none d-sm-inline-block">Routing Step Details</span>
                                    </a>
                                </li>
                                <!--
                                <li class="nav-item">
                                    <a href="#part-dwg" data-bs-toggle="tab" aria-expanded="false" class="nav-link">
                                        <span class="d-inline-block d-sm-none">Part Drawing</span>
                                        <span class="d-none d-sm-inline-block">Part Drawing</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="#task" data-bs-toggle="tab" aria-expanded="false" class="nav-link">
                                        <span class="d-inline-block d-sm-none">Task</span>
                                        <span class="d-none d-sm-inline-block">Task</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="#log" data-bs-toggle="tab" aria-expanded="false" class="nav-link">
                                        <span class="d-inline-block d-sm-none">Log</span>
                                        <span class="d-none d-sm-inline-block">Log</span>
                                    </a>
                                </li>
                                -->
                            </ul>
                        </div>
                        <!-- end -->
                        <!-- ================================ -->
                    </div>
                    <div class="row">
                        <!-- ================================ -->
                        <div class="tab-content">
                            <div class="tab-pane show active p-2" id="rs2">
                                <partial name="../Shared/_TabRoutingAvailable" model=@Model />
                            </div>
                            <div class="tab-pane p-2" id="rou-det">
                                <partial name="../Shared/_TabRoutingDetails" model=@Model />
                            </div>
                            <div class="tab-pane" id="rsd">
                                <partial name="../Shared/_TabRoutingStepDetails" model=@Model />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<partial name="../Shared/_AltRoute" />
<partial name="../Shared/_DeleteRoute" />
<partial name="../Shared/_DeleteStep" />
<partial name="../Shared/_EditRoutingName" />
<partial name="../Shared/_PreferredRouting" />
@section scripts {
    <script src="~/js/ItemMaster/supplier.js"></script>
    <script src="~/js/routing/Routing-Model.js"></script>
    <script>
        RoutingDetails = @Html.Raw(Json.Serialize(Model));
        console.log("***********");
        console.log(RoutingDetails);
        console.log("***********");
    </script>
}