CWB.App/Controllers/MastersController.cs
using CWB.App.Models.Contacts;
using CWB.App.Models.ItemMaster;
using CWB.App.Services.Masters;
using CWB.CommonUtils.Common;
using CWB.Logging;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using static System.Net.Mime.MediaTypeNames;

namespace CWB.App.Controllers
{
    public class MastersController : Controller
    {
        private readonly ILoggerManager _logger;
        private readonly IMastersServices _mastersService;
        private readonly IMachineService _machineService;
        public MastersController(ILoggerManager logger, IMachineService machineService, IMastersServices mastersService)
        {
            _logger = logger;
            _mastersService = mastersService;
            _machineService = machineService;
        }
        public IActionResult Index()
        {
            indexViewBag();
            return View();
        }

        public async Task<IActionResult> MasterDetails()
        {
            await StatusViewBagForManuf();
            return View();
        }

        public IActionResult EditPart(int partId, string partType)
        {
            if(partType.Equals("BOF"))
            {
                return RedirectToAction("EditBOF", new { partId = partId});
            }
            else if (partType.Equals("RawMaterial"))
            {
                return RedirectToAction("EditRawMaterial", new { partId = partId });
            }
            return RedirectToAction("EditManufPart", new { partId = partId });
        }

        //editmanufpart
        public async Task<IActionResult> EditManufPart(int partId)
        {
            ManufacturedPartNoDetailVM manuf = await _mastersService.GetManufPart(partId);
            await CustomerViewBag();
            await CompaniesViewBagForManuF(manuf);
            await StatusViewBagForManuf(manuf);
            return View(manuf);
        }

        public async Task<IActionResult> ManufPart(string Id)
        {
            
            await CustomerViewBag();
            await CompaniesViewBagForManuF();
            await StatusViewBagForManuf();
            return View(new ManufacturedPartNoDetailVM {MasterPartType="0", PartId=0, ManufacturedPartNoDetailId=0, ManufacturedPartType=1});
        }

        public async Task<IActionResult> EditBOF(int partId)
        {
            BoughtOutFinishDetailVM manuf = await _mastersService.GetBOFPart(partId);
            await CompaniesViewBagForBOF();
            await SupplierViewBag();
            await StatusViewBagForBOF();
            return View(manuf);
        }

        public async Task<IActionResult> EditRawMaterial(int partId)
        {
            RawMaterialDetailVM manuf = await _mastersService.GetRMPart(partId);
            await SupplierViewBag();
            await CompaniesViewBagForRawMaterial(manuf);
            await StatusViewBagForRawMaterial(manuf);
            await RawMaterialViewBags(manuf);
            return View(manuf);
        }

       

        public async Task<IActionResult> RawMaterial(string Id)
        {
            await SupplierViewBag();
            await CompaniesViewBagForRawMaterial();
            await StatusViewBagForManuf();
            await RawMaterialViewBags();
            return View(new RawMaterialDetailVM { RawMaterialDetailId=0, PartId=0});
        }

        public async Task<IActionResult> BOF(string Id)
        {
            await CompaniesViewBagForBOF();
            await StatusViewBagForBOF();
            await SupplierViewBag();
            ViewBag.BOFId = CWBAppUtils.DecodeString(Id);
            return View(new BoughtOutFinishDetailVM { BoughtOutFinishDetailId=0, PartId = 0});
        }

        #region Private Function
        private void indexViewBag()
        {
            ViewBag.IndexId = CWBAppUtils.EncodeLong(0);
        }

        public async Task<IActionResult> Customers()
        {
            var companies = await _mastersService.GetCompanies();
            return Json(companies.Where(m=>m.CompanyType.Equals("Both") || m.CompanyType.Equals("Customer")));
        }
        public async Task<IActionResult> Suppliers()
        {
            var companies = await _mastersService.GetCompanies();
            return Json(companies.Where(m => m.CompanyType.Equals("Both") || m.CompanyType.Equals("Supplier")));
        }

        [HttpGet]
        public async Task<IActionResult> Companies()
        {
            var companies = await _mastersService.GetCompanies();

            return Json(companies);

        }

        [HttpGet]
        public async Task<IActionResult> RMTypes()
        {
            var companies = await _mastersService.GetRMTypes();

            return Json(companies);

        }

        [HttpGet]
        public async Task<IActionResult> RMSpecs()
        {
            var companies = await _mastersService.GetRMSpecs();

            return Json(companies);

        }

        [HttpGet]
        public async Task<IActionResult> RMStandards()
        {
            var companies = await _mastersService.GetRMStandards();

            return Json(companies);

        }

        [HttpGet]
        public async Task<IActionResult> BaseRMs()
        {
            var companies = await _mastersService.GetBaseRMs();

            return Json(companies);

        }

        [HttpGet]
        public async Task<IActionResult> ManufacturedPartNoDetailList(long ManufPartType, string companyName)
        {
            var mfpdList = await _mastersService.GetManufacturedPartNoDetailList(ManufPartType, companyName);
            return Json(mfpdList);
        }

        /*[HttpGet]
        public async Task<IActionResult> HelloWorld(long Id)
        {
            var mfpdList = await _mastersService.HelloWorld();
            return Json(mfpdList);
        }*/

        [HttpGet]
        public async Task<IActionResult> GetUOMs()
        {
            var mfpdList = await _mastersService.GetUOMs();
            return Json(mfpdList);
        }

        [HttpPost]
        public async Task<IActionResult> AddUOM(UOMVM model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var result = await _mastersService.AddUOM(model);
            return Ok(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ManufacturedPartNoDetail(ManufacturedPartNoDetailVM model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var result = await _mastersService.ManufacturedPartNoDetail(model);
            return Ok(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MPMakeFrom(MPMakeFromVM model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var result = await _mastersService.MPMakeFrom(model);
            return Ok(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MPBOM(MPBomVM model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var result = await _mastersService.MPBOM(model);
            return Ok(result);
        }

       

        [HttpGet]
        public async Task<IActionResult> GetMakeFrom(string Id)
        {
            var mpmakefromlist = await _mastersService.GetMakeFrom(Id);
            return Ok(mpmakefromlist);

        }
        [HttpGet]
        public async Task<IActionResult> GetBOM(string Id)
        {
            var mpmakefromlist = await _mastersService.GetBOM(Id);
            return Ok(mpmakefromlist);

        }


        [HttpGet]
        public async Task<IActionResult> BOFS()
        {
            var mpmakefromlist = await _mastersService.BOFS();
            return Ok(mpmakefromlist);

        }

        [HttpGet]
        public async Task<IActionResult> SupplierRMS(string supplierId)
        {
            var mfpdList = await _mastersService.SupplierRMS(supplierId);
            return Ok(mfpdList);
        }

        [HttpGet]
        public async Task<IActionResult> mpdlist()
        {
            var mfpdList = await _mastersService.GetAllManufacturedPartNoDetailList();
            return Json(mfpdList);
        }
        //GetAllManufacturedPartNoDetailList


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RawMaterialDetail(RawMaterialDetailVM model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var result = await _mastersService.RawMaterialDetail(model);
            return Ok(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PartPurchase(PartPurchaseDetailsVM model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var result = await _mastersService.PartPurchase(model);
            return Ok(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemPartPurchase(PartPurchaseDetailsVM model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var result = await _mastersService.RemPartPurchase(model);
            return Ok(result);
        }

       

        [HttpGet]
        public async Task<IActionResult> PartPurchases()
        {
            var mfpdList = await _mastersService.PartPurchases();

CWB.App/Views/Masters/EditBOF.cshtml
@{
    ViewData["Title"] = "Edit Item Master - BOF";
}
@model CWB.App.Models.ItemMaster.BoughtOutFinishDetailVM
<partial name="BOF" model=@Model />

@section scripts {
    <script src="~/js/addfunctions.js"></script>
    <script src="~/js/ItemMaster/supplier.js"></script>
    <script src="~/js/ItemMaster/rmselects.js"></script>
    <script src="~/js/contact-model.js"></script>
    <script src="~/js/ItemMaster/BOF-model.js"></script>
    <script src="~/js/ItemMaster/purchasedetails.js"></script>
    <script src="~/js/contacts.js"></script>
    <script>
        var modelObj = @Html.Raw(Json.Serialize(Model));
        modelObj["Edit"] = true;
        //$('#BOFform').validate();
    </script>
}

CWB.App/Views/Masters/EditManufPart.cshtml
@{
    ViewData["Title"] = "Edit Item Master - Manufactured Part";
    
}
@model CWB.App.Models.ItemMaster.ManufacturedPartNoDetailVM
<partial name="ManufPart" model=@Model />


@section scripts {
    <script src="~/js/addfunctions.js"></script>
    <script src="~/js/ItemMaster/supplier.js"></script>
    <script src="~/js/ItemMaster/rmselects.js"></script>
    <script src="~/js/contact-model.js"></script>
    <script src="~/js/ItemMaster/ManufPart-model.js"></script>
    <script src="~/js/contacts.js"></script>
    <script src="~/js/searchparts.js"></script>
    <script src="~/js/searchpartsbof.js"></script>
    <script>
        var modelObj = @Html.Raw(Json.Serialize(Model));
        modelObj["Edit"] = true;
   //     $('#ManufPartForm').validate();
    </script>
}

CWB.App/Views/Masters/EditRawMaterial.cshtml
@{
    ViewData["Title"] = "Item Master - Raw Material";
}
@model CWB.App.Models.ItemMaster.RawMaterialDetailVM
<partial name="RawMaterial" model=@Model/>

@section scripts {
    <script src="~/js/addfunctions.js"></script>
    <script src="~/js/ItemMaster/supplier.js"></script>
    <script src="~/js/ItemMaster/rmselects.js"></script>
    <script src="~/js/contact-model.js"></script>
    <script src="~/js/ItemMaster/RawMaterial-model.js"></script>
    <script src="~/js/ItemMaster/purchasedetails.js"></script>
    <script src="~/js/contacts.js"></script>
    <script>
        var modelObj = @Html.Raw(Json.Serialize(Model));
        modelObj["Edit"] = true;
        //$('#RawMetform').validate();
    </script>
}

CWB.App/Views/Masters/Index.cshtml
@{
    ViewData["Title"] = "Item Master";
}
<input value="M-IM" type="hidden" id="hdn-nav-menu" />
<div class="content">
    <div class="row">
        <div class="col-xl-12 col-md-12 col-sm-12 col-xs-12">
            <!-- ================= -->
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <h5>Item Master Action List</h5>
                    </div>
                    <!-- end row -->
                    <div class="row mt-2">
                        <div class="col-md-3">
                            <div class="widget-simple text-center card btn btn-outline-info">
                                <a asp-action="MasterDetails">
                                    <div class="card-body">
                                        <h5><br>View / Edit Part Numbers<br><br></h5>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <!-- end -->
                        <div class="col-md-3">
                            <div class="widget-simple text-center card btn btn-outline-info">
                                <a asp-action="ManufPart" asp-route-id="@ViewBag.IndexId">
                                    <div class="card-body">
                                        <h5><br>Create New Manf Part No <br><br></h5>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <!-- end -->
                        <div class="col-md-3">
                            <div class="widget-simple text-center card btn btn-outline-info">
                                <a asp-action="RawMaterial" asp-route-id="@ViewBag.IndexId">
                                    <div class="card-body">
                                        <h5>Create New Raw Material <br><br> Part No</h5>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <!-- end -->
                        <div class="col-md-3">
                            <div class="widget-simple text-center card btn btn-outline-info">
                                <a asp-action="BOF" asp-route-id="@ViewBag.IndexId">
                                    <div class="card-body">
                                        <h5>Create New Bought Out Finish <br><br> (BOF) Part No</h5>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <!-- end -->
                    </div>
                    <!-- end row -->
                </div>
            </div>
            <!-- end card body -->
            <!-- ================= -->
        </div>
        <!-- end card -->
        <!-- ======================================================================== -->
    </div>
    <!-- end col -->
</div>

CWB.App/Views/Masters/ManufPart.cshtml
@{
    ViewData["Title"] = "Item Master - Manufactured Part";
    
}

@model CWB.App.Models.ItemMaster.ManufacturedPartNoDetailVM
<input value="M-IM" type="hidden" id="hdn-nav-menu" />
<div class="content" id="ManufPartMain">
    <div class="row">
        
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <!-- ================ -->
                    <div class="row m-0">
                        <div class="col-md-9">
                            <ul class="nav nav-tabs nav-pills navtab-bg">
                                <li class="nav-item" id="TabMPMain">
                                    <a href="#tab-1" aria-expanded="false" class="nav-link active">
                                        <span class="d-inline-block d-sm-none">Basic Info</span>
                                        <span class="d-none d-sm-inline-block">Basic Information</span>
                                    </a>
                                </li>
                                <li class="nav-item" id="TabHeadMakefrom">
                                    <a href="#tab-2" id="navHeadMakefrom" aria-expanded="true" class="nav-link ">
                                        <span class="d-inline-block d-sm-none">Make from</span>
                                        <span class="d-none d-sm-inline-block">Make from</span>
                                    </a>
                                </li>
                                <li class="nav-item" id="TabHeadBOM">
                                    <a href="#tab-3" id="navHeadBOM" aria-expanded="false" class="nav-link">
                                        <span class="d-inline-block d-sm-none">BOM</span>
                                        <span class="d-none d-sm-inline-block">BOM</span>
                                    </a>
                                </li>
                                <li class="nav-item" id="TabHeadBalloon">
                                    <a href="#tab-4" aria-expanded="false" class="nav-link">
                                        <span class="d-inline-block d-sm-none">Balloon</span>
                                        <span class="d-none d-sm-inline-block">Balloon</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-3 text-end">
                            <a asp-action="Index" asp-controller="Masters">
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </a>
                        </div>
                    </div>
                    <!-- ===============================================================  -->
                    <!-- ===============================================================  -->
                    
                    <div class="tab-content">
                        <!-- ================ -->
                        <div class="tab-pane show active" id="tab-1">
                            <partial name="../Shared/_ManuF_Tab1" model=@Model/>
                            <!-- ===================  -->
                            <div class="row mt-2">
                                <partial name="_ReferenceDocuments" />
                            </div>
                            <!-- end row -->
                        </div>
                        <!-- ================ -->
                        <div class="tab-pane" id="tab-2">
                            <partial name="../Shared/_ManuF_Tab2" model='new CWB.App.Models.ItemMaster.MPMakeFromVM{}' />
                        </div>
                        <!-- ================ -->
                        <div class="tab-pane" id="tab-3">       
                            <partial name="../Shared/_ManuF_Tab3" model='new CWB.App.Models.ItemMaster.MPBomVM{}' />
                        </div>
                        <!-- ======================= -->
                        <div class="tab-pane" id="tab-4"></div>
                        <!-- ======================= -->
                    </div>
            

                    <!-- ================ -->
                </div>
            </div>
        </div>
        <!-- ====== end col =========== -->
    </div>
    <!-- end row -->
</div>


<partial name="_ManuF_Templates" />

<partial name="_EditBOM" />
<partial name="_EditMakeFrom"/>
<partial name="_DeleteBOM"/>
<partial name="_DeleteMakeFrom"/>

<partial name="_ReferenceDocumentUpload" />
<partial name="../Shared/_AddUOM" />
<partial name="../Shared/_CustomerSuppliedRM" />
<partial name="../Shared/_ExistingPart" />
<partial name="../Shared/_ExistingPartBOF" />
<partial name="../Shared/_ContactsDialog" model='new CWB.App.Models.Contacts.CompanyVM{CompanyId=0,DivisionId=0,Location=""}' />
<partial name="../Shared/_RawMaterialSelection" />



@section scripts {
    <script src="~/js/addfunctions.js"></script>
    <script src="~/js/ItemMaster/supplier.js"></script>
    <script src="~/js/ItemMaster/rmselects.js"></script>
    <script src="~/js/contact-model.js"></script>
    <script src="~/js/ItemMaster/ManufPart-model.js"></script>
    <script src="~/js/contacts.js"></script>
    <script src="~/js/searchparts.js"></script>
    <script src="~/js/searchpartsbof.js"></script>
    <script>
        var modelObj = @Html.Raw(Json.Serialize(Model));
        modelObj["Edit"] = false;
   
    </script>
}

CWB.App/Views/Masters/RawMaterial_bak .cshtml
@{
    ViewData["Title"] = "Item Master - Raw Material";
}
@model CWB.App.Models.ItemMaster.RawMaterialDetailVM
<input value="M-IM" type="hidden" id="hdn-nav-menu" />
<!-- Left Sidebar End -->
<!-- ============================================================== -->
<!-- Start Page Content here -->
<!-- ============================================================== -->
<div class="content">
</div>
  
<partial name="_ReferenceDocumentUpload" />
@section scripts {
<script src="~/js/ItemMaster/RawMaterial-model.js"></script>
}

    

CWB.App/Views/Masters/RawMaterial_barebone.cshtml
@{
    ViewData["Title"] = "Item Master - Raw Material";
}
@model CWB.App.Models.ItemMaster.RawMaterialDetailVM
<input value="M-IM" type="hidden" id="hdn-nav-menu" />
<form method="post" id="RawMetform">
    <table>
        <tr>
        </tr>
        <tr>
            <input type="text" value="1" id="Status" name="Status" />
            <br>
            <br>
            <input type="text" value="Spec" id="MaterialSpec" name="MaterialSpec" />
            <br>
            <br>
            <input type="Date" value="" id="RevDate" name="RevDate" />
            <br>
            <br>
            <input type="text" value="100987" id="RevNo" name="RevNo" />
            <br>
            <br>
            <input type="text" value="1" id="RawMaterialMadeType" name="RawMaterialMadeType" />
            <br>
            <br>
            <input type="text" value="1" id="RawMaterialTypeId" name="RawMaterialTypeId" />
            <br>
            <br>
            <input type="text" hidden value="1009" id="InHousePartNo" name="InHousePartNo" />
            <br>
            <br>
            <input type="text" value="Desc" id="PartDescription" name="PartDescription" />
            <br>
            <br>
            <input type="text" value="1" id="BaseRawMaterialId" name="BaseRawMaterialId" />
            <br>
            <br>
            <input type="text" value="Notes..." id="RawMaterialNotes" name="RawMaterialNotes" />
            <br>
            <br>
            <input type="text" hidden value="10" id="RawMaterialWeight" name="RawMaterialWeight" />
            <br>
            <br>
            <input type="text" hidden value="1" id="Standard" name="Standard" />
            <br>
            <br>
            <input type="text" hidden value="1" id="PurchaseDetailId" name="PurchaseDetailId" />
            <br>
            <br>
            <input type="button" id="btnRawMaterialDetailSubmit" value="Save" text="Save" />
            <br>
            <br>
        </tr>
    </table>
</form>

<partial name="_ReferenceDocumentUpload" />
@section scripts {
<script src="~/js/ItemMaster/RawMaterial-model.js"></script>
}

    

CWB.App/Views/Masters/_ReferenceDocumentUpload.cshtml
<div id="part-reference-doc-model" class="modal fade" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="standard-modalLabel">Document Upload</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <!-- ------- -->
                    <div class="col-md-12">
                        <!-- =========== -->
                        <div class="row mt-2">
                            <label class="col-md-4 form-label mb-2">File Content / Comment <span class="text-danger"> * </span></label>
                            <div class="col-md-8 mb-2" title="Indicate the File Content or any relevant info about the Document" data-plugin="tippy" data-tippy-placement="top">
                                <textarea name="comment" form="usrform" id="simpleinput" class="form-control form-control-sm"></textarea>
                            </div>
                        </div>
                        <!-- =========== -->
                        <!-- =========== -->
                        <div class="row">
                            <label class="col-md-4 form-label mb-2">Document Type <span class="text-danger"> * </span></label>
                            <div class="col-md-8 mb-2" title="Select the Document Type" data-plugin="tippy" data-tippy-placement="top">
                                <select class="form-select form-select-sm" aria-label="form-select-sm">
                                    <option value="">3D</option>
                                    <option value="">2D</option>
                                    <option value="">jpg</option>
                                </select>
                            </div>
                            <!-- -------  -->
                        </div>
                        <!-- =========== -->
                        <!-- =========== -->
                        <div class="row mt-2">
                            <div class="col-md-7">
                                <div class="fileupload btn btn-sm btn-info waves-effect w-100" title="" data-plugin="tippy" data-tippy-placement="top">
                                    <span><i class="mdi mdi-cloud-upload me-1"></i>Document Upload</span>
                                    <input type="file" class="upload">
                                </div>
                            </div>
                            <!-- ----------- -->
                            <div class="col-md-5 text-end">
                                <button class="btn btn-sm btn-primary" title="Use to Save the entered data" data-plugin="tippy" data-tippy-placement="top">Save</button>
                            </div>
                        </div>
                        <!-- =========== -->
                        <!-- =========== -->
                        <div class="row mt-2 display-none">
                            <div class="col-md-5">
                                <button class="btn btn-sm btn-info w-100">Create New Document</button>
                            </div>
                            <div class="col-md-5">
                                <button class="btn btn-sm btn-purple w-100" data-bs-toggle="modal" data-bs-target="#task-rou">Task Document Creation  <span class="badge bg-primary rounded-circle noti-icon-badge m-l-10">5</span>  </button>
                            </div>
                        </div>
                        <!-- =========== -->
                    </div>
                    <!-- ------- -->
                </div>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>